layout_spectrum: 0.7433491956033181
typography_spectrum: 0.9797198375791201
color:
  lightness: 0.834685070036016
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  saturation: 0.8478033688524277
  brandStrength: 0.11670271164433349
  rhythmicContrast: 0.23847466187413302
content_rating:
  adult: false
github: true
opengraph: {}
analytics: {}
author:
  name: Giovani di Gesu
  email: contact@giovanidigesu.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a5f65829-0c46-4344-b46b-de0abd42d653.png
name: giovanidigesu
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About
    id: 7214412d-59b3-4fdc-9a02-1fc9e9f90e90
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/309fdd40-fe32-4fec-8697-5dfaaa36cf20.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: giovanidigesu
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/536bad21-2ded-440e-a7c9-1ba1b9be6d94.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/536bad21-2ded-440e-a7c9-1ba1b9be6d94.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d955a1ec-4c96-43d5-b5a7-49a04c115108.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d955a1ec-4c96-43d5-b5a7-49a04c115108.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Growth, strategy, operations, organization, business models, and business
  technology.
purpose:
  - type: contact
    url: 'mailto:contact@giovanidigesu.com'
    label: Contact me
